// <auto-generated />
using System;
using BroxDistribution;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BroxDistribution1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260104101224_AdminAndSoftDelete")]
    partial class AdminAndSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BroxDistribution.Models.ContactForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReplied")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplyMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WineBrand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WineCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WineCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WineName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("WineYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ContactForms");
                });

            modelBuilder.Entity("BroxDistribution.Models.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AlcoholPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Grape")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlcoholPercentage = 13.5m,
                            Brand = "Château Margaux",
                            Category = "Red",
                            Country = "France",
                            Description = "Elegant and complex with notes of blackcurrant, cedar, and vanilla. A legendary First Growth Bordeaux with exceptional aging potential.",
                            Grape = "Cabernet Sauvignon",
                            ImageUrl = "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
                            IsDeleted = false,
                            Name = "Château Margaux",
                            Price = 850.00m,
                            Region = "Bordeaux",
                            Year = 2015
                        },
                        new
                        {
                            Id = 2,
                            AlcoholPercentage = 14.5m,
                            Brand = "Giacomo Conterno",
                            Category = "Red",
                            Country = "Italy",
                            Description = "Powerful yet refined with intense cherry, rose, and tar. The king of Italian wines with remarkable structure and longevity.",
                            Grape = "Nebbiolo",
                            ImageUrl = "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80",
                            IsDeleted = false,
                            Name = "Barolo Riserva",
                            Price = 320.00m,
                            Region = "Piedmont",
                            Year = 2016
                        },
                        new
                        {
                            Id = 3,
                            AlcoholPercentage = 14.5m,
                            Brand = "Opus One Winery",
                            Category = "Red",
                            Country = "USA",
                            Description = "A Bordeaux-Napa collaboration showcasing dark fruit, espresso, and silky tannins. Modern luxury in a bottle.",
                            Grape = "Cabernet Sauvignon",
                            ImageUrl = "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800&q=80",
                            IsDeleted = false,
                            Name = "Opus One",
                            Price = 420.00m,
                            Region = "Napa Valley",
                            Year = 2018
                        },
                        new
                        {
                            Id = 4,
                            AlcoholPercentage = 14.5m,
                            Brand = "Penfolds",
                            Category = "Red",
                            Country = "Australia",
                            Description = "Australia's most iconic wine with concentrated blackberry, chocolate, and exotic spices. Bold and age-worthy.",
                            Grape = "Shiraz",
                            ImageUrl = "https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=800&q=80",
                            IsDeleted = false,
                            Name = "Penfolds Grange",
                            Price = 650.00m,
                            Region = "South Australia",
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            AlcoholPercentage = 14.0m,
                            Brand = "Bodegas Vega Sicilia",
                            Category = "Red",
                            Country = "Spain",
                            Description = "Spain's most prestigious wine with deep cherry, leather, and tobacco. Extended aging creates extraordinary complexity.",
                            Grape = "Tempranillo",
                            ImageUrl = "https://images.unsplash.com/photo-1504279577054-acfeccf8fc52?w=800&q=80",
                            IsDeleted = false,
                            Name = "Vega Sicilia Único",
                            Price = 480.00m,
                            Region = "Ribera del Duero",
                            Year = 2010
                        },
                        new
                        {
                            Id = 6,
                            AlcoholPercentage = 13.0m,
                            Brand = "Domaine de la Romanée-Conti",
                            Category = "Red",
                            Country = "France",
                            Description = "The pinnacle of Pinot Noir with ethereal red fruit, earth, and spice. Exceptionally rare and sought-after.",
                            Grape = "Pinot Noir",
                            ImageUrl = "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=800&q=80",
                            IsDeleted = false,
                            Name = "Pinot Noir Reserve",
                            Price = 1200.00m,
                            Region = "Burgundy",
                            Year = 2019
                        },
                        new
                        {
                            Id = 7,
                            AlcoholPercentage = 13.5m,
                            Brand = "López de Heredia",
                            Category = "Red",
                            Country = "Spain",
                            Description = "Traditional Rioja with dried cherry, vanilla, and leather. Elegant aging in American oak barrels.",
                            Grape = "Tempranillo",
                            ImageUrl = "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80",
                            IsDeleted = false,
                            Name = "Rioja Gran Reserva",
                            Price = 85.00m,
                            Region = "Rioja",
                            Year = 2011
                        },
                        new
                        {
                            Id = 8,
                            AlcoholPercentage = 13.0m,
                            Brand = "Domaine William Fèvre",
                            Category = "White",
                            Country = "France",
                            Description = "Pure expression of Chardonnay with mineral-driven citrus, green apple, and oyster shell. Razor-sharp precision.",
                            Grape = "Chardonnay",
                            ImageUrl = "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80",
                            IsDeleted = false,
                            Name = "Chablis Grand Cru",
                            Price = 120.00m,
                            Region = "Burgundy",
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            AlcoholPercentage = 13.5m,
                            Brand = "Domaine Leflaive",
                            Category = "White",
                            Country = "France",
                            Description = "World-class white Burgundy with hazelnut, white peach, and wet stone. Incredible depth and elegance.",
                            Grape = "Chardonnay",
                            ImageUrl = "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=800&q=80",
                            IsDeleted = false,
                            Name = "Puligny-Montrachet",
                            Price = 280.00m,
                            Region = "Burgundy",
                            Year = 2019
                        },
                        new
                        {
                            Id = 10,
                            AlcoholPercentage = 8.0m,
                            Brand = "Weingut Egon Müller",
                            Category = "White",
                            Country = "Germany",
                            Description = "Off-dry Riesling with honeyed apricot, lime zest, and slate. Perfect balance of sweetness and acidity.",
                            Grape = "Riesling",
                            ImageUrl = "https://images.unsplash.com/photo-1608181715566-82b365885969?w=800&q=80",
                            IsDeleted = false,
                            Name = "Riesling Spätlese",
                            Price = 95.00m,
                            Region = "Mosel",
                            Year = 2021
                        },
                        new
                        {
                            Id = 11,
                            AlcoholPercentage = 13.0m,
                            Brand = "Cloudy Bay",
                            Category = "White",
                            Country = "New Zealand",
                            Description = "Iconic New Zealand Sauvignon with vibrant passionfruit, grapefruit, and fresh herbs. Crisp and refreshing.",
                            Grape = "Sauvignon Blanc",
                            ImageUrl = "https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=800&q=80",
                            IsDeleted = false,
                            Name = "Cloudy Bay Sauvignon Blanc",
                            Price = 42.00m,
                            Region = "Marlborough",
                            Year = 2022
                        },
                        new
                        {
                            Id = 12,
                            AlcoholPercentage = 13.5m,
                            Brand = "Domaine des Comtes Lafon",
                            Category = "White",
                            Country = "France",
                            Description = "Rich yet refined with buttered toast, lemon curd, and hazelnut. Classic white Burgundy luxury.",
                            Grape = "Chardonnay",
                            ImageUrl = "https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=800&q=80",
                            IsDeleted = false,
                            Name = "Meursault",
                            Price = 195.00m,
                            Region = "Burgundy",
                            Year = 2020
                        },
                        new
                        {
                            Id = 13,
                            AlcoholPercentage = 12.5m,
                            Brand = "Moët & Chandon",
                            Category = "Sparkling",
                            Country = "France",
                            Description = "Prestige cuvée Champagne with brioche, white flowers, and citrus. Elegant mousse and remarkable aging potential.",
                            Grape = "Chardonnay",
                            ImageUrl = "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800&q=80",
                            IsDeleted = false,
                            Name = "Dom Pérignon",
                            Price = 220.00m,
                            Region = "Champagne",
                            Year = 2012
                        },
                        new
                        {
                            Id = 14,
                            AlcoholPercentage = 12.0m,
                            Brand = "Krug",
                            Category = "Sparkling",
                            Country = "France",
                            Description = "Multi-vintage blend of extraordinary complexity with toasted nuts, honey, and dried fruits. The ultimate Champagne.",
                            Grape = "Pinot Noir",
                            ImageUrl = "https://images.unsplash.com/photo-1624362169293-f5d00c0bb81a?w=800&q=80",
                            IsDeleted = false,
                            Name = "Krug Grande Cuvée",
                            Price = 280.00m,
                            Region = "Champagne",
                            Year = 2015
                        },
                        new
                        {
                            Id = 15,
                            AlcoholPercentage = 12.0m,
                            Brand = "Bollinger",
                            Category = "Sparkling",
                            Country = "France",
                            Description = "Powerful and vinous with apple, pear, and spice. A favorite of James Bond and connoisseurs alike.",
                            Grape = "Pinot Noir",
                            ImageUrl = "https://images.unsplash.com/photo-1560148489-a48d1076e7e6?w=800&q=80",
                            IsDeleted = false,
                            Name = "Bollinger Special Cuvée",
                            Price = 75.00m,
                            Region = "Champagne",
                            Year = 2018
                        },
                        new
                        {
                            Id = 16,
                            AlcoholPercentage = 12.5m,
                            Brand = "Ca' del Bosco",
                            Category = "Sparkling",
                            Country = "Italy",
                            Description = "Italy's answer to Champagne with refined bubbles, white peach, and almond. Elegant and sophisticated.",
                            Grape = "Chardonnay",
                            ImageUrl = "https://images.unsplash.com/photo-1598254436156-edo8bcd561bf?w=800&q=80",
                            IsDeleted = false,
                            Name = "Franciacorta Brut",
                            Price = 55.00m,
                            Region = "Lombardy",
                            Year = 2019
                        },
                        new
                        {
                            Id = 17,
                            AlcoholPercentage = 13.0m,
                            Brand = "Château d'Esclans",
                            Category = "Rosé",
                            Country = "France",
                            Description = "The most famous Provence rosé with strawberry, watermelon, and fresh herbs. Crisp and refreshing summer wine.",
                            Grape = "Grenache",
                            ImageUrl = "https://images.unsplash.com/photo-1598524722937-291d2efee71d?w=800&q=80",
                            IsDeleted = false,
                            Name = "Château d'Esclans Whispering Angel",
                            Price = 28.00m,
                            Region = "Provence",
                            Year = 2022
                        },
                        new
                        {
                            Id = 18,
                            AlcoholPercentage = 13.5m,
                            Brand = "Domaines Ott",
                            Category = "Rosé",
                            Country = "France",
                            Description = "Premium Provence rosé in an iconic bottle. Delicate red fruit, citrus, and mineral notes.",
                            Grape = "Grenache",
                            ImageUrl = "https://images.unsplash.com/photo-1598032895397-b9c35df5e0f0?w=800&q=80",
                            IsDeleted = false,
                            Name = "Domaines Ott Château de Selle",
                            Price = 48.00m,
                            Region = "Provence",
                            Year = 2022
                        },
                        new
                        {
                            Id = 19,
                            AlcoholPercentage = 13.5m,
                            Brand = "Château d'Yquem",
                            Category = "Dessert",
                            Country = "France",
                            Description = "The world's greatest sweet wine with honeyed apricot, caramel, and botrytis complexity. Liquid gold.",
                            Grape = "Sémillon",
                            ImageUrl = "https://images.unsplash.com/photo-1560148489-a48d1076e7e6?w=800&q=80",
                            IsDeleted = false,
                            Name = "Château d'Yquem",
                            Price = 420.00m,
                            Region = "Sauternes",
                            Year = 2014
                        },
                        new
                        {
                            Id = 20,
                            AlcoholPercentage = 5.0m,
                            Brand = "Royal Tokaji",
                            Category = "Dessert",
                            Country = "Hungary",
                            Description = "Legendary Hungarian nectar with intense sweetness, orange marmalade, and spice. Ultra-rare and precious.",
                            Grape = "Furmint",
                            ImageUrl = "https://images.unsplash.com/photo-1606216794079-e28fcdbb0ca2?w=800&q=80",
                            IsDeleted = false,
                            Name = "Royal Tokaji Essencia",
                            Price = 680.00m,
                            Region = "Tokaj",
                            Year = 2013
                        });
                });

            modelBuilder.Entity("BroxDistribution1.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 4, 11, 12, 18, 525, DateTimeKind.Local).AddTicks(1540),
                            Email = "admin@broxdistribution.com",
                            PasswordHash = "$2a$11$pERXaBXtJ./YHxs9.htyFOK5EePmaB4NVUT8lED.P.qfqwGhxuNuO",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
